apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gcs5nk57y-nodejs
  janus-idp.io/tekton: gcs5nk57y-nodejs
  backstage.io/kubernetes-id: gcs5nk57y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gcs5nk57y-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
